spring.application.name=RAGinAction
server.port=0
spring.ai.ollama.chat.model=qwen
logging.level.org.zalando.logbook: TRACE
logbook.format.style=http

spring.cloud.function.definition=\
  fileSupplier|\
  documentReader|\
  splitter|\
  titleDeterminer|\
  vectorStoreConsumer

file.supplier.directory=c:/temp/dropoff
file.supplier.filename-regex=.*\.(pdf|docx|txt)

